/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.fidentis.gui.comparison_batch;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author zanri
 */
public class HistogramJPanel extends javax.swing.JPanel {

    private List<Float> values;
    private int width, height;
    private Color color;
    
    /**
     * Creates new form HistogramJPanel
     */
    public HistogramJPanel() {
        initComponents();
        this.setBackground(Color.WHITE);
        this.values = new ArrayList<>();
        this.color = Color.WHITE;
    }
    
    public void setSize(int width, int height){
        this.width = width;
        this.height = height+10;
        this.setPreferredSize(new Dimension(width, height));
    }
    
    public void setColor(Color color){
        this.color = color;
        this.repaint();
    }
            
    
    public void setValues(List<Float> values){
        this.values = selectionSort(values);
        this.repaint();
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);  
        
        int textPosX = 10;
        int textPosY1 = 35;
        int textPosY2 = height - 35;

        float maximal = (float) Math.ceil(values.get(0));
        float minimal = Math.round(values.get(values.size()-1))-1f;
        
        if(g instanceof Graphics2D)
        {
            Graphics2D g2 = (Graphics2D)g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                                RenderingHints.VALUE_ANTIALIAS_ON);

            g2.drawString(""+maximal,textPosX,textPosY1); 
            g2.drawString(""+minimal,textPosX,textPosY2); 
        }
        
        int deltaX = (int)Math.ceil((this.width-40) / values.size());
        int deltaY = (int)Math.round(Math.ceil((this.height) / values.get(0)));
        
        for (int i = 0; i < values.size(); i++){
            float value = values.get(values.size() - i -1);
            int x = 30 + deltaX*i;
            int y = 35+(int)Math.round(Math.ceil((values.get(0) - value)*deltaY));

            int heightRec = height - 35 - y;
            int widthRec = deltaX;
            
            g.setColor(color);
            g.fillRect(x,y,widthRec,heightRec);
            
            g.setColor(Color.black);
            g.drawRect(x,y,widthRec,heightRec);
        }
    }
    
    
    public static List<Float> selectionSort(List<Float> array) {
        for (int i = 0; i < array.size() - 1; i++) {
            int maxIndex = i;
            for (int j = i + 1; j < array.size(); j++) {
                if (array.get(j) > array.get(maxIndex)) maxIndex = j;
            }
            float tmp = array.get(i);
            array.set(i, array.get(maxIndex));
            array.set(maxIndex, tmp);
        } 
        return array;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
