/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.fidentis.gui.comparison_batch;

/**
 *
 * @author zanri
 */
public class LocalAreasSelectedAreaJPanel extends javax.swing.JPanel {

    private String text;
    
    /**
     * Creates new form LocalAreasSelectedPointJPanel
     */
    public LocalAreasSelectedAreaJPanel() {
        initComponents();
        text = "Point(x,y,z): [-1, -1, -1]";
    }
    
    public void SetArea(String area){
        this.labelPositionOfPoint.setText("Area "+ area+"");
    }
    
    public void SetPosition(double x, double y){
        this.labelPositionOfPoint1.setText("Point(x,y,z): ["+x+", "+y+"]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPositionOfPoint = new javax.swing.JLabel();
        labelPositionOfPoint1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(labelPositionOfPoint, org.openide.util.NbBundle.getMessage(LocalAreasSelectedAreaJPanel.class, "LocalAreasSelectedAreaJPanel.labelPositionOfPoint.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(labelPositionOfPoint1, org.openide.util.NbBundle.getMessage(LocalAreasSelectedAreaJPanel.class, "LocalAreasSelectedAreaJPanel.labelPositionOfPoint1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPositionOfPoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPositionOfPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelPositionOfPoint)
                .addGap(38, 38, 38)
                .addComponent(labelPositionOfPoint1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPositionOfPoint;
    private javax.swing.JLabel labelPositionOfPoint1;
    // End of variables declaration//GEN-END:variables
}
